// CamiTube — app logic
// Reads the pre-built videos.json (generated by GitHub Actions using yt-dlp,
// no API key involved) and renders it. Watch progress and status are tracked
// locally in this browser via the YouTube IFrame Player API.

let channels = [];        // [{ channelId, handle, title }]
let pool = [];             // all videos, sorted newest first
let activeFilter = "all";  // "all" (last LATEST_WINDOW_DAYS days) or a channelId (full history)
let shown = 0;              // how many of the current filtered list are rendered
let nameByChannelId = {};  // channelId -> short display name

const $ = (sel) => document.querySelector(sel);
const grid = $("#grid");
const statusEl = $("#status");
const loadMoreBtn = $("#loadMoreBtn");
const filterRow = $("#filterRow");
const updatedAtEl = $("#updatedAt");

// ---------- Watch progress (stored locally in this browser only) ----------

const PROGRESS_LS_KEY = "camitube_progress";
const WATCHED_THRESHOLD = 0.9; // 90%+ watched counts as "watched"

function loadProgressStore() {
  try {
    return JSON.parse(localStorage.getItem(PROGRESS_LS_KEY) || "{}");
  } catch (err) {
    return {};
  }
}

let progressStore = loadProgressStore();

function getProgress(videoId) {
  return progressStore[videoId] || null;
}

function saveProgress(videoId, position, duration) {
  if (!duration || duration <= 0) return;
  progressStore[videoId] = {
    position: Math.max(0, Math.min(position, duration)),
    duration,
    updatedAt: Date.now(),
  };
  localStorage.setItem(PROGRESS_LS_KEY, JSON.stringify(progressStore));
}

function getStatus(videoId) {
  const p = getProgress(videoId);
  if (!p || !p.duration) return "new";
  const ratio = p.position / p.duration;
  if (ratio >= WATCHED_THRESHOLD) return "watched";
  if (p.position >= 1) return "watching";
  return "new";
}

function getProgressRatio(videoId) {
  const p = getProgress(videoId);
  if (!p || !p.duration) return 0;
  return Math.min(1, p.position / p.duration);
}

function setStatus(text, isError) {
  if (!text) { statusEl.hidden = true; return; }
  statusEl.hidden = false;
  statusEl.textContent = text;
  statusEl.classList.toggle("error", !!isError);
}

function formatDate(iso) {
  const d = new Date(iso);
  return d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
}

function formatRelative(iso) {
  const seconds = Math.floor((Date.now() - new Date(iso).getTime()) / 1000);
  if (seconds < 60) return "just now";
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `${days}d ago`;
  const weeks = Math.floor(days / 7);
  if (weeks < 5) return `${weeks}w ago`;
  const months = Math.floor(days / 30);
  if (months < 12) return `${months}mo ago`;
  const years = Math.floor(days / 365);
  return `${years}y ago`;
}

function formatDuration(totalSeconds) {
  if (totalSeconds === null || totalSeconds === undefined) return null;
  const total = Math.round(totalSeconds);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const ss = String(s).padStart(2, "0");
  if (h > 0) return `${h}:${String(m).padStart(2, "0")}:${ss}`;
  return `${m}:${ss}`;
}

function currentList() {
  if (activeFilter === "all") {
    const cutoff = Date.now() - LATEST_WINDOW_DAYS * 24 * 60 * 60 * 1000;
    return pool.filter((v) => new Date(v.publishedAt).getTime() >= cutoff);
  }
  return pool.filter((v) => v.channelId === activeFilter);
}

function renderFilters() {
  filterRow.innerHTML = "";
  const latestPill = document.createElement("button");
  latestPill.className = "pill" + (activeFilter === "all" ? " active" : "");
  latestPill.textContent = "Latest videos";
  latestPill.addEventListener("click", () => setFilter("all"));
  filterRow.appendChild(latestPill);

  channels.forEach((c) => {
    const pill = document.createElement("button");
    pill.className = "pill" + (activeFilter === c.channelId ? " active" : "");
    pill.textContent = nameByChannelId[c.channelId] || c.title;
    pill.addEventListener("click", () => setFilter(c.channelId));
    filterRow.appendChild(pill);
  });
}

function setFilter(channelId) {
  activeFilter = channelId;
  shown = 0;
  renderFilters();
  renderGrid(true);
}

function renderGrid(reset) {
  const list = currentList();
  if (reset) grid.innerHTML = "";

  if (list.length === 0) {
    setStatus(
      activeFilter === "all"
        ? "No videos from the last week — pick a channel above to see its full history."
        : "No videos yet — check back after the next scheduled update."
    );
    loadMoreBtn.hidden = true;
    return;
  }
  setStatus("");

  const nextShown = Math.min(shown + PAGE_SIZE, list.length);
  list.slice(shown, nextShown).forEach((video) => grid.appendChild(renderCard(video)));
  shown = nextShown;

  loadMoreBtn.hidden = shown >= list.length;
}

function renderCard(video) {
  const card = document.createElement("button");
  card.className = "card";
  card.type = "button";
  card.dataset.videoId = video.videoId;

  const thumbWrap = document.createElement("div");
  thumbWrap.className = "thumb-wrap";
  const img = document.createElement("img");
  img.src = video.thumb;
  img.alt = "";
  img.loading = "lazy";
  thumbWrap.appendChild(img);

  if (video.membersOnly) {
    const membersBadge = document.createElement("span");
    membersBadge.className = "badge-members";
    membersBadge.textContent = "Members only";
    thumbWrap.appendChild(membersBadge);
  }

  const durationLabel = formatDuration(video.duration);
  if (durationLabel) {
    const durationBadge = document.createElement("span");
    durationBadge.className = "badge-duration";
    durationBadge.textContent = durationLabel;
    thumbWrap.appendChild(durationBadge);
  }

  const statusBadge = document.createElement("span");
  statusBadge.className = "badge-status";
  thumbWrap.appendChild(statusBadge);

  const progressBar = document.createElement("span");
  progressBar.className = "progress-bar";
  thumbWrap.appendChild(progressBar);

  const title = document.createElement("div");
  title.className = "card-title";
  title.textContent = video.title;

  const meta = document.createElement("div");
  meta.className = "card-meta";
  const channelName = document.createElement("span");
  channelName.textContent = nameByChannelId[video.channelId] || video.channelTitle;
  const date = document.createElement("span");
  date.className = "card-date";
  date.textContent = formatRelative(video.publishedAt);

  meta.appendChild(channelName);
  meta.appendChild(date);

  card.appendChild(thumbWrap);
  card.appendChild(title);
  card.appendChild(meta);

  applyStatusToCard(card, video.videoId);

  card.addEventListener("click", () => openPlayer(video));
  return card;
}

function applyStatusToCard(cardEl, videoId) {
  const status = getStatus(videoId);
  const badge = cardEl.querySelector(".badge-status");
  const bar = cardEl.querySelector(".progress-bar");

  cardEl.classList.remove("status-watching", "status-watched");

  if (status === "watched") {
    cardEl.classList.add("status-watched");
    if (badge) badge.textContent = "✓ Watched";
    if (bar) bar.style.width = "100%";
  } else if (status === "watching") {
    cardEl.classList.add("status-watching");
    if (badge) badge.textContent = "Watching";
    if (bar) bar.style.width = `${Math.round(getProgressRatio(videoId) * 100)}%`;
  } else if (bar) {
    bar.style.width = "0%";
  }
}

function refreshCardStatus(videoId) {
  const cardEl = grid.querySelector(`[data-video-id="${videoId}"]`);
  if (cardEl) applyStatusToCard(cardEl, videoId);
}

// ---------- Player ----------

const playerOverlay = $("#playerOverlay");
const playerFrame = $("#playerFrame");
const playerTitle = $("#playerTitle");
const playerSub = $("#playerSub");

let ytPlayer = null;
let progressInterval = null;
let currentVideo = null;

// The YouTube IFrame API script (loaded in index.html) calls this when ready.
let ytApiReady = false;
window.onYouTubeIframeAPIReady = () => { ytApiReady = true; };

function openPlayer(video) {
  currentVideo = video;

  const progress = getProgress(video.videoId);
  let resumeSeconds = 0;
  if (progress && progress.duration > 0) {
    const ratio = progress.position / progress.duration;
    if (ratio < WATCHED_THRESHOLD && progress.position > 5) {
      resumeSeconds = Math.floor(progress.position);
    }
  }

  playerFrame.innerHTML = '<div id="ytplayer"></div>';
  playerTitle.textContent = video.title;
  playerSub.textContent = `${nameByChannelId[video.channelId] || video.channelTitle} · ${formatDate(video.publishedAt)}`;
  playerOverlay.hidden = false;

  if (window.YT && window.YT.Player) {
    createYtPlayer(video, resumeSeconds);
  } else {
    waitForYtApi(video, resumeSeconds, Date.now());
  }
}

function waitForYtApi(video, resumeSeconds, startedAt) {
  if (currentVideo !== video) return; // player was closed / switched while waiting
  if (window.YT && window.YT.Player) {
    createYtPlayer(video, resumeSeconds);
  } else if (Date.now() - startedAt > 4000) {
    createFallbackIframe(video, resumeSeconds); // progress won't be tracked in this fallback
  } else {
    setTimeout(() => waitForYtApi(video, resumeSeconds, startedAt), 150);
  }
}

function createYtPlayer(video, resumeSeconds) {
  ytPlayer = new YT.Player("ytplayer", {
    videoId: video.videoId,
    playerVars: { autoplay: 1, start: resumeSeconds, rel: 0 },
    events: { onStateChange: onPlayerStateChange },
  });
}

function createFallbackIframe(video, resumeSeconds) {
  const iframe = document.createElement("iframe");
  iframe.src = `https://www.youtube.com/embed/${video.videoId}?autoplay=1&start=${resumeSeconds}`;
  iframe.title = video.title;
  iframe.allow = "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture";
  iframe.allowFullscreen = true;
  playerFrame.innerHTML = "";
  playerFrame.appendChild(iframe);
}

function onPlayerStateChange(e) {
  if (e.data === YT.PlayerState.PLAYING) {
    saveCurrentProgress();
    startProgressTracking();
  } else if (e.data === YT.PlayerState.PAUSED) {
    stopProgressTracking();
    saveCurrentProgress();
  } else if (e.data === YT.PlayerState.ENDED) {
    stopProgressTracking();
    if (currentVideo && ytPlayer) {
      const duration = ytPlayer.getDuration();
      if (duration > 0) saveProgress(currentVideo.videoId, duration, duration);
      refreshCardStatus(currentVideo.videoId);
    }
  }
}

function startProgressTracking() {
  stopProgressTracking();
  progressInterval = setInterval(saveCurrentProgress, 5000);
}

function stopProgressTracking() {
  if (progressInterval) {
    clearInterval(progressInterval);
    progressInterval = null;
  }
}

function saveCurrentProgress() {
  if (!ytPlayer || !currentVideo || typeof ytPlayer.getCurrentTime !== "function") return;
  try {
    const position = ytPlayer.getCurrentTime();
    const duration = ytPlayer.getDuration();
    if (duration > 0) {
      saveProgress(currentVideo.videoId, position, duration);
      refreshCardStatus(currentVideo.videoId);
    }
  } catch (err) {
    // player not ready yet — ignore, next tick will retry
  }
}

function closePlayer() {
  stopProgressTracking();
  saveCurrentProgress();
  if (ytPlayer && typeof ytPlayer.destroy === "function") {
    try { ytPlayer.destroy(); } catch (err) { /* already gone */ }
  }
  ytPlayer = null;
  currentVideo = null;
  playerOverlay.hidden = true;
  playerFrame.innerHTML = "";
}

window.addEventListener("beforeunload", () => {
  if (progressInterval) saveCurrentProgress();
});

$("#closePlayerBtn").addEventListener("click", closePlayer);
playerOverlay.addEventListener("click", (e) => {
  if (e.target === playerOverlay) closePlayer();
});
document.addEventListener("keydown", (e) => {
  if (e.key === "Escape" && !playerOverlay.hidden) closePlayer();
});

// ---------- Load more ----------

loadMoreBtn.addEventListener("click", () => renderGrid(false));

// ---------- Boot ----------

async function boot() {
  setStatus("Loading videos…");
  try {
    const res = await fetch("./videos.json", { cache: "no-store" });
    if (!res.ok) throw new Error(`videos.json request failed (${res.status})`);
    const data = await res.json();

    channels = data.channels || [];
    nameByChannelId = {};
    channels.forEach((c) => {
      nameByChannelId[c.channelId] = DISPLAY_NAMES[c.handle] || c.title;
    });

    pool = (data.videos || []).slice().sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt));

    if (data.generatedAt) {
      updatedAtEl.textContent = `Updated ${formatDate(data.generatedAt)}`;
    }

    renderFilters();
    shown = 0;
    renderGrid(true);
  } catch (err) {
    setStatus(`Couldn't load the video list: ${err.message}`, true);
  }
}

boot();
